### PR TITLE
Use the latest conda-build

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
@msarahan am I seeing a `conda-build` or `conda` bug here?

```
Error: The following specifications were found to be in conflict:
  - bob.io.image -> libpng 1.6*|1.6.21*
  - libpng 1.6.21*
  - python 3.5*
```

**Comment by 183amir** [comment]
@pelson do you think if I remove the old `bob.io.image` packages, it would solve my problem here?

**Comment by pelson** [comment]
Yes, it seems plausible.

```
$ conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --package bob.io.image --dependencies libpng --platform osx-64
Fetching package metadata: ..
bob.io.image 2.0.6 py27_0 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py27_2 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py27_jpeg8_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py27_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py27_jpeg9_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py27_jpeg9_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_0 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py34_2 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py34_jpeg8_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py34_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg9_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py34_jpeg9_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_0 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py35_2 osx-64   : libpng 1.6*
bob.io.image 2.0.6 py35_jpeg8_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py35_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg9_3 osx-64: libpng 1.6*
bob.io.image 2.0.6 py35_jpeg9_4 osx-64: libpng 1.6.21*
```

And 

```
conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --package bob.io.image --dependencies libpng --platform linux-64
Fetching package metadata: ..
bob.io.image 2.0.5 py27_0 linux-64 : libpng
bob.io.image 2.0.5 py27_1 linux-64 : libpng 1.6*
bob.io.image 2.0.5 py27_2 linux-64 : libpng 1.6*
bob.io.image 2.0.5 py34_0 linux-64 : libpng
bob.io.image 2.0.5 py34_1 linux-64 : libpng 1.6*
bob.io.image 2.0.5 py34_2 linux-64 : libpng 1.6*
bob.io.image 2.0.5 py35_0 linux-64 : libpng
bob.io.image 2.0.5 py35_1 linux-64 : libpng 1.6*
bob.io.image 2.0.5 py35_2 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py27_0 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py27_1 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py27_2 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py27_jpeg8_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py27_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py27_jpeg9_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py27_jpeg9_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_0 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py34_1 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py34_2 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py34_jpeg8_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py34_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg9_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py34_jpeg9_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_0 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py35_1 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py35_2 linux-64 : libpng 1.6*
bob.io.image 2.0.6 py35_jpeg8_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py35_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg9_3 linux-64: libpng 1.6*
bob.io.image 2.0.6 py35_jpeg9_4 linux-64: libpng 1.6.21*
```

Are the `libpng 1.6*` the problem distributions?

**Comment by 183amir** [comment]
The problem is `libpng 1.6.17` and `libpng 1.6.21` are incompatible. So the ones that are pinned on `libpng 1.6*` would not really work.

**Comment by 183amir** [comment]
So @pelson are you going to remove them?

**Comment by pelson** [comment]
I found removing these to be highly prone to human error, but have done so:

```
$ pelson@~/dev/conda-forge> conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --package bob.io.image --dependencies libpng --platform linux-64
Fetching package metadata: ..
bob.io.image 2.0.6 py27_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py27_jpeg9_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg9_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg8_4 linux-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg9_4 linux-64: libpng 1.6.21*

$ pelson@~/dev/conda-forge> conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --package bob.io.image --dependencies libpng --platform osx-64
Fetching package metadata: ..
bob.io.image 2.0.6 py27_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py27_jpeg9_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py34_jpeg9_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg8_4 osx-64: libpng 1.6.21*
bob.io.image 2.0.6 py35_jpeg9_4 osx-64: libpng 1.6.21*
```

I'll be keen to automate this to avoid the human error risk in the future.

Let me know if that helps.

**Comment by 183amir** [comment]
Removing those packages fixed the mac build, no need to merge this.

**Pull request closed without merging**
